/**
 * Automatically translated from Java to Java
 * 
 * Original file: src/main/java/com/example/library/BookRepository.java
 * Module: BookRepository
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.ssbt.ipp.model;

import com.converted.app.model.Book;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.ArrayList;

@Repository
public class BookRepository {
    private List<Book> books;

    public BookRepository() {
        this.books = new ArrayList<>();
    }
    
    public void save(Book book) {
        books.add(book);
    }
    
    public Book findByIsbn(String isbn) {
        for (Book book : books) {
            if (book.getIsbn().equals(isbn)) {
                return book;
            }
        }
        return null;
    }
    
    public List<Book> findAll() {
        return new ArrayList<>(books);
    }
    
    public void delete(String isbn) {
        books.removeIf(book -> book.getIsbn().equals(isbn));
    }
}