/**
 * Automatically translated from Java to Java
 * 
 * Original file: src/main/java/com/example/library/User.java
 * Module: User
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.ssbt.ipp.model;

import java.util.ArrayList;
import java.util.List;

public class User {
    private String userId;
    private String name;
    private String email;
    private List<String> borrowedBooks;
    private final int maxBooksAllowed = 5;
    
    public User(String userId, String name, String email) {
        this.userId = userId;
        this.name = name;
        this.email = email;
        this.borrowedBooks = new ArrayList<>();
    }
    
    public String getUserId() { return userId; }
    public String getName() { return name; }
    public String getEmail() { return email; }
    
    public boolean canBorrowMore() {
        return borrowedBooks.size() < maxBooksAllowed;
    }
    
    public boolean borrowBook(String isbn) {
        if (canBorrowMore() && !borrowedBooks.contains(isbn)) {
            borrowedBooks.add(isbn);
            return true;
        }
        return false;
    }
    
    public boolean returnBook(String isbn) {
        return borrowedBooks.remove(isbn);
    }
    
    @Override
    public String toString() {
        return "User ID: " + userId + "\n" +
               "Name: " + name + "\n" +
               "Email: " + email + "\n" +
               "Borrowed books: " + borrowedBooks.size() + "/" + maxBooksAllowed;
    }
}